server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    session:
      timeout: 30m
  port: 8080

# JSP, mustache 원하는거 사용
spring:
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
  h2:
    console:
      enabled: true
#  sql:
#    init:
#      data-locations:
#        - classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    
    